language: cpp
notifications:
  email: false
sudo: false
dist: trusty
services:
- docker
matrix:
  include:
  - os: linux
    compiler: clang
    env: CXX=clang++ CC=clang
  - os: linux
    compiler: gcc-6
    env: CXX=g++ CC=gcc
script:
- docker run -e "CXX" -e "CC" -e "CI" -e "TRAVIS" -e "TRAVIS_COMMIT" -e "TRAVIS_TAG"
  -e "TRAVIS_BUILD_NUMBER" -e "REPOSITORY_KEY" --tty=false -it -v $PWD:/src --workdir
  /src bentou/ubuntu-bionic-dev python3 ./build.py
before_script:
- docker pull bentou/ubuntu-bionic-dev
- docker ps -a
- mkdir bin
env:
  global: H3l+NCd900ZcmlUtnbZmlzk6BbqeLlcSF45nEazC8+D3pbtsI0I7iIjTDVLR7Km6/0y2VHR5mOQ/+2ch9PAGP5JH+YDEYpY0pp3NbUM94binOsChMkq0vw7LDtMiaC3A6+2iGfdET8X7TNLBRRh19Rw0udcfLODKRMJUhBh6hiKVEpSYAl8seQSfuLuSXJWhHjr+3mk2nZkmAlBN4dJU919xy5196LlXH7VnEKjtUPf3a+5aDRVMw/wSrXG9vzD6Oqc6PzaOVEp4JmMfeDjqQn/lzH3Kf1GGAn+gP5kA7gkk8DdjBUpVJ0PQGSn1X7w2R+eYtVX93hd3LOYKrWYjnjMGPT/yi9xQEA/lQilsFj8PJThOgcoX+zDvF/DlgorI4Mh5IsBWovf/JFQGphTFQIBBSZcSg7OKILAJiJhm8XOZuZYpTUM1Msp31Z2oeqDtAchxT8HSEtbugBk5cCtxq4Eua9NFDJfLWgf4Wi0k0qfpTVAms29lr2g8PcCDExWTu89tWnLZVnO8Krsuw8MwLxgBnnZjOSsj4Zrq8XgoWFy7qOFFlNTwQLwxrq7yfZqPWKZJ2Hm3a4aGj4GxLgkPhpHK7Js2gfNFcSLK+68kreoWQqxFxTBFUqV7P96nc6AuDoPzVP4n8o7l53ap2/1s3hhZ7TJve3OmgCSEce4PgTg=
  matrix:
    secure: GfhChySiaRz8DuAwBuv4lWjr+ddUHg0q8Qose6mwT3wQg+LciiaYMGvNnmPpgo+O1o+T6x6YXhpTxWcHLiy8Z05iCe1snJ4sAYZasrigDplrTN4gLdNrXp3w7c7xbPB3Z9QUr05ubozVqXPTYZrEU9qgnvrUUnUPH8AmB/5uPIFxmy0fwM5QoZTkxSjQZ4ElJXA4tB7KTNT5X2q0RsSPtjRo3u0R6Ib+EajV2d2adAq2pOd806/aUmlWFsd3VDLM3uwrzF6F6fbCNS4bOIi4PfnpS/IbWBh0/PVtU4YkdUtFvTqAq6w1Jz6zBHA4xgCR3XiqXEXGLMMVl6MJ1F46bEX2kQw4StgzMkmIdmCT4/3lFX2qtDakyi5WMM63AF+3xVFWvKs9go2R5W5qc5kjLqyN9xDPVW8KNorIoO2VGoR+v/xNGNV7IFvLnKIvhDWcRH4Vl0Cqe8jlPhQakQUxrWhfX3vMgEbJ4tJZZp+txSyWr1nIGhK2GYLprOde6lqYqnRduwmA0ln4l8TDXqB1fM6aMeg4aPjwc9Snm1GXLO9cSUJGyUeNaWAeSacqxj3FHnewI3M9w0DojvXcOAIz3/1d0oH4urnSLV6lfaWZoRfcZYDJOxdqWAOij0FZmwVKws967oDx0m8U+Aukxd8wJo50A7fyUH6AXRzcmTUi92s=
