version: 1.0.{build}

image:
  - Visual Studio 2017

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

platform: x64
configuration: Release

environment:
  PYTHON: "C:\\Python27"

install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan --upgrade
  - cmd: pip.exe install conan_package_tools
  - cmd: refreshenv
  - cmd: conan user # It creates the conan data directory

build_script:
  - cmd: conan --version
  - cmd: conan create . bentoudev/yage

on_success:
  - cmd: conan remote add yage https://api.bintray.com/conan/bentoudev/yage
  - cmd: conan upload Assimp/0.1@bentoudev/yage --all -r=yage